services:
  localstack:
    image: localstack/localstack:4.14
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,apigatewayv2,sqs,dynamodb,iam,sns,cloudwatch,sts,logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
